name: Check Tickets
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Check Tickets
        run: node index.js
        env:
          INPUT_PRODUCT_ID: "210031"
          INPUT_SCHEDULE_ID: "100002"
          INPUT_SEAT_ID: "10008"
          INPUT_MESSAGE: "抢票"
          INPUT_SLACK_INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
