name: workflow
on: push
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
      - name: Prepare
        run: npm ci
      - name: Lint
        uses: mooyoul/tslint-actions@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '*.ts'
      - name: Build
        run: npm run build
      - name: Check Tickets
        run: |
          export INPUT_PRODUCT_ID="210031"
          export INPUT_SCHEDULE_ID="100002"
          export INPUT_SEAT_ID="10008"
          export INPUT_MESSAGE="抢票"
          export SLACK_INCOMING_WEBHOOK_URL="${{ secrets.SLACK_WEBHOOK_URL }}"
          node /home/eee/IdeaProjects/melon-ticket-actions/index.js
