name: Check Tickets
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # 每5分钟运行一次
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Check Tickets
        run: node index.js
        env:
          INPUT_PRODUCT_ID: ${{ secrets.INPUT_PRODUCT_ID }}
          INPUT_SCHEDULE_ID: ${{ secrets.INPUT_SCHEDULE_ID }}
          INPUT_SEAT_ID: ${{ secrets.INPUT_SEAT_ID }}
          INPUT_MESSAGE: ${{ secrets.INPUT_MESSAGE }}
          INPUT_SLACK_INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
